/*csd*/
/**
 * tp 3.0
 * tp 模板引擎，最简洁高效的js模板引擎
 * tp 可应用于Node.js，也可以在浏览器环境下使用。
 * 作者：侯锋
 * 邮箱：admin@xhou.net
 * 网站：http://houfeng.net , http://houfeng.net/tp
 */
(function(f){f.option={codeBegin:"{#",codeEnd:"#}"};function e(i){i=i.replace(new RegExp("\\{1}","gim"),"\\\\");i=i.replace(new RegExp("\r{1}","gim"),"");i=i.replace(new RegExp("\n{1}","gim"),"\\n");i=i.replace(new RegExp("\r{1}","gim"),"\\r");i=i.replace(new RegExp('"{1}',"gim"),'\\"');return i;}function d(i){return i.replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&");}function h(j,k){try{return j();}catch(i){i.message=i.message||"";i.stack=i.stack||"";i.message=k+" : "+i.message+"\r\n    "+i.stack;throw i;}}var c={};function b(k,i){i=i||c;for(var j in k){i[j]=k[j];}}function a(){var i=function(j){i.buffer.push(j);};b(c,i);i.buffer=[];return i;}f.extend=b;f.compile=function(r,q){r=r||"";q=q||{};q.codeBegin=q.codeBegin||f.option.codeBegin;q.codeEnd=q.codeEnd||f.option.codeEnd;var k=new RegExp(q.codeBegin,"gim");var m=new RegExp(q.codeEnd,"gim");var n=new RegExp("("+q.codeBegin+"(.|\n|\r)*?"+q.codeEnd+")","gim");var j=["$.model=this;with($.model){"];var l=r.match(n);var s=r.replace(n,"▎").split("▎");for(var p=0;p<s.length;p++){j.push('$("'+e(s[p])+'");');if(l&&l[p]){j.push(l[p].replace(k,"").replace(m,"")+";");}}j.push('};return $.buffer.join("");');var o=function(i){return h(function(){return o.src.call((i||{}),o.handler)||"";},"Template execute error");};h(function(){o.handler=a();o.src=new Function("$",j.join(""));},"Template compile error");return o;};f.parse=function(l,j,k){var i=f.compile(l,k);return i(j);};if(typeof window!=="undefined"&&window.document){f.query=(f.option.query||function(i){return window.document.getElementById(i);});var g={};f.bind=function(i){i=i||{};i.el=i.el||i.element;i.el=(typeof i.el==="string")?f.query(i.el):i.el;i.tp=i.tp||i.template||i.el;i.tp=(typeof i.tp==="string")?(f.query(i.tp)||i.tp):i.tp;if(!i.tp||!i.el){return;}g[i.tp]=g[i.tp]||f.compile(d(i.tp.innerHTML||i.tp),i);if(i.append){i.el.innerHTML+=g[i.tp](i.model);}else{i.el.innerHTML=g[i.tp](i.model);}};window.tp=f;}})((function(){var a=(typeof exports==="undefined")?{}:exports;if(typeof define==="function"&&define.amd){define("tp",[],function(){return a;});}return a;})());